//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentTable
    {
        public int Appointment_Id { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public Nullable<int> Patient_Id { get; set; }
        public Nullable<int> Doctor_Schedule_Id { get; set; }
        public string Reason_For_Appointment { get; set; }
        public string Appointment_Time { get; set; }
        public Nullable<int> Appointment_Status_Id { get; set; }
        public string Doctor_Comment { get; set; }
    
        public virtual Appointment_Status Appointment_Status { get; set; }
        public virtual Doctor_Schedule_Table Doctor_Schedule_Table { get; set; }
        public virtual Doctor_Table Doctor_Table { get; set; }
        public virtual PatientTable PatientTable { get; set; }
    }
}
