//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Schedule_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor_Schedule_Table()
        {
            this.AppointmentTables = new HashSet<AppointmentTable>();
        }
    
        public int Doctor_Schedule_Id { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public string Schedule_Date { get; set; }
        public string Day { get; set; }
        public string Time_start { get; set; }
        public string Time_end { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTable> AppointmentTables { get; set; }
        public virtual Doctor_Table Doctor_Table { get; set; }
    }
}
