//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthcareDBEntities : DbContext
    {
        public HealthcareDBEntities()
            : base("name=HealthcareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTables { get; set; }
        public virtual DbSet<Appointment_Status> Appointment_Status { get; set; }
        public virtual DbSet<AppointmentTable> AppointmentTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Doctor_Schedule_Table> Doctor_Schedule_Table { get; set; }
        public virtual DbSet<Doctor_Table> Doctor_Table { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<Patient_Gender> Patient_Gender { get; set; }
        public virtual DbSet<Patient_Status> Patient_Status { get; set; }
        public virtual DbSet<PatientTable> PatientTables { get; set; }
        public virtual DbSet<Role_Type> Role_Type { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
    }
}
