//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientTable()
        {
            this.AppointmentTables = new HashSet<AppointmentTable>();
        }
    
        public int Patient_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Date_of_Birth { get; set; }
        public Nullable<int> Patient_Gender_Type_Id { get; set; }
        public string Patient_Address { get; set; }
        public string Patient_Phone_No { get; set; }
        public Nullable<int> Patient_Marital_Status_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTable> AppointmentTables { get; set; }
        public virtual Patient_Gender Patient_Gender { get; set; }
        public virtual Patient_Status Patient_Status { get; set; }
        public virtual User_Table User_Table { get; set; }
    }
}
